name: hatchworks
favicon: null
layout_spectrum: 0.5708394043613225
typography_spectrum: 0.15196604980155826
title: Family Photo Restoration
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.03695852402597666
  lightness: 0.3726858759764582
  saturation: 0.4425428977701813
  rhythmicContrast: 0.01580576691776514
purpose: []
